//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlunoMembo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlunoMembo()
        {
            this.Participandoes = new HashSet<Participando>();
        }
    
        public System.Guid IdAlunoMembo { get; set; }
        public string emaila { get; set; }
        public string senha { get; set; }
        public string Nome { get; set; }
        public string curso { get; set; }
        public string periodo { get; set; }
        public string campus { get; set; }
        public byte situacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participando> Participandoes { get; set; }
    }
}
