//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avaliador()
        {
            this.Projetoes = new HashSet<Projeto>();
        }
    
        public System.Guid IdAvaliador { get; set; }
        public string emailAval { get; set; }
        public string nome { get; set; }
        public string senha { get; set; }
        public string areaAtuacao { get; set; }
        public string formacao { get; set; }
        public byte situacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projeto> Projetoes { get; set; }
    }
}
