//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participando
    {
        public System.Guid Professor_idProfessor { get; set; }
        public System.Guid AlunoMembo_idAlunoMembo { get; set; }
        public System.Guid Projeto_idProjeto { get; set; }
        public System.Guid Avaliador_idAvaliador { get; set; }
    
        public virtual AlunoMembo AlunoMembo { get; set; }
        public virtual Avaliador Avaliador { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual Projeto Projeto { get; set; }
    }
}
