//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resposta
    {
        public System.Guid IdResposta { get; set; }
        public Nullable<System.Guid> IdProjeto { get; set; }
        public Nullable<byte> IdBloco { get; set; }
        public string Resposta1 { get; set; }
    
        public virtual Projeto Projeto { get; set; }
    }
}
