//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class s2aeiDBEntities : DbContext
    {
        public s2aeiDBEntities()
            : base("name=s2aeiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administracao> Administracaos { get; set; }
        public virtual DbSet<AlunoMembo> AlunoMemboes { get; set; }
        public virtual DbSet<Avaliador> Avaliadors { get; set; }
        public virtual DbSet<Participando> Participandoes { get; set; }
        public virtual DbSet<Professor> Professors { get; set; }
        public virtual DbSet<Projeto> Projetoes { get; set; }
    }
}
